import type { ContentBlock } from '@shared/content-schema';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { notFound } from 'next/navigation';

import { BlockEditor } from '@/components/BlockEditor';
import { Button } from '@/components/ui/Button';
import { BLANK_PAYLOADS, BLOCK_TYPE_LABELS } from '@/lib/blockDefaults';
import {
  createBlockWithPayload,
  getDraftStatus,
  getEditingVersionId,
  getNavbarVariants,
} from '@/lib/actions';
import { createClient } from '@/lib/supabase/server';

/**
 * Draft block creation page. Nothing is persisted in the database until the
 * user clicks "Créer le bloc" — if they navigate back to the chapter, no
 * empty row is left behind.
 *
 * The route uses a synthetic `draft-<type>` blockId locally, just so the
 * iframe override messages have a stable id; the real id is generated by
 * `createBlockWithPayload` on first save.
 */
export default async function NewBlockPage({
  params,
  searchParams,
}: {
  params: Promise<{ slug: string; chapterSlug: string }>;
  searchParams: Promise<{ type?: string }>;
}) {
  const raw = await params;
  const slug = decodeURIComponent(raw.slug);
  const chapterSlug = decodeURIComponent(raw.chapterSlug);
  const sp = await searchParams;
  const type = (sp.type ?? 'text') as ContentBlock['type'];

  if (!BLANK_PAYLOADS[type as keyof typeof BLANK_PAYLOADS]) notFound();

  const supabase = await createClient();

  const { data: parcours } = await supabase
    .from('parcours')
    .select('id')
    .eq('slug', slug)
    .maybeSingle();

  // Prefer the draft version when one exists, fall back to published.
  const versionId = await getEditingVersionId(slug);

  const { data: chapter } = await supabase
    .from('chapter')
    .select('id, slug, title')
    .eq('version_id', versionId ?? '')
    .eq('slug', chapterSlug)
    .maybeSingle();

  if (!chapter) notFound();

  const { data: variablesRows } = await supabase
    .from('variable')
    .select('id, key, label, type, options')
    .eq('parcours_id', parcours?.id)
    .order('key', { ascending: true });

  const variables = (variablesRows ?? []).map((v) => ({
    id: v.id,
    key: v.key,
    label: v.label,
    type: v.type as 'boolean' | 'enum' | 'string' | 'number',
    options: (v.options as Array<{ value: string; label: string }>) ?? [],
  }));

  const { data: allChapters } = await supabase
    .from('chapter')
    .select('id, slug, title, "order", section_label, section_order')
    .eq('version_id', versionId ?? '')
    .order('order', { ascending: true });
  const chapters = (allChapters ?? []).map((c) => ({
    id: c.id,
    slug: c.slug,
    title: c.title,
    sectionLabel: (c as { section_label?: string | null }).section_label ?? null,
    sectionOrder: (c as { section_order?: number | null }).section_order ?? null,
  }));

  const draftId = `draft-${type}`;
  const initialPayload = BLANK_PAYLOADS[type as keyof typeof BLANK_PAYLOADS] as Record<
    string,
    unknown
  >;

  async function createAction(payload: Record<string, unknown>): Promise<string> {
    'use server';
    return await createBlockWithPayload(slug, chapterSlug, chapter!.id, type, payload);
  }
  // saveAction is unused in draft mode (createAction takes precedence) but the
  // BlockEditor prop is required — we provide a no-op.
  async function saveAction(_payload: Record<string, unknown>) {
    'use server';
  }

  // Draft id (if any) so the iframe previews the draft version, not the live.
  const draftStatus = await getDraftStatus(slug);
  const navbarVariants = await getNavbarVariants(slug);

  return (
    <div className="space-y-6">
      <div>
        <Link href={`/parcours/${slug}/chapters/${chapterSlug}`}>
          <Button variant="outline" size="sm" className="gap-1.5">
            <ArrowLeft className="h-3.5 w-3.5" />
            Retour au chapitre <span className="text-muted-foreground">(sans enregistrer)</span>
          </Button>
        </Link>
        <h2 className="mt-3 text-lg font-semibold">
          Nouveau bloc{' '}
          <span className="font-mono text-sm">
            {BLOCK_TYPE_LABELS[type as keyof typeof BLOCK_TYPE_LABELS] ?? type}
          </span>
        </h2>
      </div>

      <BlockEditor
        blockId={draftId}
        chapterSlug={chapterSlug}
        parcoursSlug={slug}
        isNew
        type={type}
        initialPayload={initialPayload}
        variables={variables}
        saveAction={saveAction}
        createAction={createAction}
        editingVersionId={draftStatus.draftVersionId}
        publishedVersionId={draftStatus.publishedVersionId}
        chapters={chapters}
        navbarVariants={navbarVariants}
      />
    </div>
  );
}
