name: Pull request

on:
  pull_request: {}

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: beemojs/conventional-pr-action@v3
        with:
          config-preset: angular
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
